# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  scraper:
    image: jaredzg/dota-scraper
    build:
      context: ./dota-scraper
    environment:
      DOTA_DB_HOST: postgres:5432
      DOTA_DB_USER: database
      DOTA_DB_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - type: volume
        source: scraper-items
        target: /app/data
        volume:
          nocopy: true
      - type: bind
        source: ./dota-scraper/src
        target: /app/src
    ports:
      - 8000:5432
    secrets:
      - postgres-password
    depends_on:
      postgres:
        condition: service_healthy

  database:
    image: jaredzg/dota-database
    build:
      context: ./dota-database
    environment:
      - NODE_ENV=development
      - DOTA_DB_HOST=postgres
      - DOTA_DB_NAME=dota-database
      - DOTA_DB_USER=database
      - DOTA_DB_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - type: bind
        source: ./dota-database/src
        target: /app/src
      - type: bind
        source: ./dota-database/configs
        target: /app/configs
      - type: bind
        source: ./dota-database/drizzle
        target: /app/drizzle
    ports:
      - 8001:5432
    secrets:
      - postgres-password
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dota-database
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  scraper-items:
  postgres-data:

secrets:
  postgres-password:
    file: ./dota-database/secrets/password.txt
